apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    server-type: naam-dev-api-backend
    type: dev
  name: naam-dev-api-backend-test
  namespace: naam-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      server-type: naam-dev-api-backend
      type: dev
  template:
    metadata:
      labels:
        server-type: naam-dev-api-backend
        type: dev
    spec:
      containers:
      - image: dev-registry.sarv.com/naam-dev/helloapp:dev-1.0.13
        name: naam-dev-api-backend
        resources:
          limits:
            cpu: "2"
            memory: 1Gi
          requests:
            cpu: "0.5"
            memory: 128Mi
      imagePullSecrets:
      - name: imgcred1
      nodeSelector:
        node-role.kubernetes.io/worker: w1
